### ISSUE TITLE
Editor does not get dirty on value changes in RadioButtonGroup

### ISSUE THREAD

**Issue by olaf-2** [vaadin/vaadin-crud-flow#114] opened 2018-11-30 09:51 UTC
When a new value is selected in a RadioButtonGroup the save button remains disabled. Attached is a patch with a RadioButtonGroup in the Person editor in the demo.

[radiobutton.txt](https://github.com/vaadin/vaadin-crud-flow/files/2632771/radiobutton.txt)

**Comment by johannest** [comment] 2019-03-07 14:48
Workaround, thanks @alvarezguille : `crud.getElement().executeJavaScript("this.__isDirty=true;");`

**Comment by alvarezguille** [comment] 2019-03-08 16:39
This issue is currently blocked by https://github.com/vaadin/vaadin-radio-button/issues/103

We will evaluate some alternative solutions in the meantime

**Comment by olaf-2** [comment] 2019-03-13 05:34
> Workaround, thanks @alvarezguille : `crud.getElement().executeJavaScript("this.__isDirty=true;");`

Thank you very much. That helps. Also I use it as a workaround for https://github.com/vaadin/vaadin-crud-flow/issues/78 until the fix mentioned there makes it into the official release.

**Comment by alvarezguille** [comment] 2019-03-25 14:47
The root cause for this issue was fixed and released in [vaadin-radio-button#1.2.0]( https://github.com/vaadin/vaadin-radio-button/releases/tag/v1.2.0)

Since it required a new minor version, 1.2.0 won't be included in Vaadin 13 maintenance release

Java users can override version for `vaadin-radio-button` webjar artifact
```
<groupId>org.webjars.bowergithub.vaadin</groupId>
<artifactId>vaadin-radio-button</artifactId>
<version>1.2.0</version>
```

**Closed** 2019-03-25 14:47 UTC
Labels: BFP
