### ISSUE TITLE
setValue in a form doesn't make editor dirty

### ISSUE THREAD

**Issue by letsdense** [vaadin/vaadin-crud-flow#78] opened 2018-10-18 09:51 UTC
Using Testbench API setValue method for a TextFieldElement inside an editor doesn't make the editor dirty. The save button keeps be disabled. And Cancel click closes the editor with no confirmation shown.

However, it's possible to click on the disabled Save button via testbench API

**Comment by oluwasayo** [comment] 2018-11-06 14:20
Listening to `value-changed` event on the form does not fix this issue as Polymer does not retarget property-changed events so they don't propagate across shadow dom boundaries.

**Comment by alexberazouski** [comment] 2018-11-07 11:59
Remove todo and add a test showing a `discard changes` confirmation dialog, once the issue is fixed
https://github.com/vaadin/vaadin-crud-flow/blob/1.0.0/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/CustomGridIT.java#L31

**Comment by olaf-2** [comment] 2019-01-17 11:41
Currently this is really a pain for me since I fill many fields programatically. In my case the user scans a barcode with the camera (web cam or mobile phone). The app sets the barcode as well as other field values with data from the server based on this barcode. After that the user must manually edit another field because otherwise he would not be able to save the data since the save button is not enabled. Is it somehow possible to programatically switch the editor to state dirty?

**Comment by alvarezguille** [comment] 2019-03-05 16:18
In TestBench case TextFieldElement and other elements does the following to setValue
https://github.com/vaadin/vaadin-components-testbench/blob/master/vaadin-components-testbench/src/main/java/com/vaadin/flow/component/textfield/testbench/TextFieldElement.java#L32-L37
To make the form dirty the change event should bubble
```
    public void dispatchEvent(String eventType, boolean bubbles) {
        executeScript(
                "arguments[0].dispatchEvent(new CustomEvent(arguments[1], { bubbles: arguments[2] }));",
                this, eventType, bubbles);
    }
``` 
This kind of API could be added to `TestBenchElement`

-----------
@olaf-2 dispatching change event that bubbles should also help when setting the form data programmatically

**Comment by alvarezguille** [comment] 2019-03-08 16:27
This should be fixed by updating https://github.com/vaadin/vaadin-components-testbench/releases/tag/2.0.2

**Comment by olaf-2** [comment] 2019-03-13 05:35
> @olaf-2 dispatching change event that bubbles should also help when setting the form data programmatically

Thank you very much. Currently I use https://github.com/vaadin/vaadin-crud-flow/issues/114#issuecomment-470554378 as a workaround.

**Closed** 2019-03-19 15:55 UTC

**Comment by alvarezguille** [comment] 2019-03-19 16:03
@olaf-2 we closed the issue once TextFieldElement was fixed and the proper test added
I'm not sure which way you're setting value, but if your issue is not TestBench related please create a new issue detailing how you're updating data that doesn't make the editor dirty
